import { DEFAULT_REPORT_DATA, type ReportData } from "@/lib/report-steps";

export interface DemoReport {
  slug: string;
  title: string;
  industry: string;
  onlinePath: string;
  revision: string;
  workflowSummary: string;
  reportData: ReportData;
  evidenceFiles: Array<{
    filename: string;
    content?: string;
    stepId: string;
    publicPath?: string;
    mimeType?: string;
  }>;
}

function reportData(overrides: Partial<ReportData>): ReportData {
  return { ...DEFAULT_REPORT_DATA, ...overrides };
}

export const DEMO_REPORTS: Record<string, DemoReport> = {
  automotive: {
    slug: "automotive",
    title: "Automotive 8D - CNC Housing Burr at Customer Incoming Inspection",
    industry: "Automotive machining",
    onlinePath: "/8d-report-example/automotive",
    revision: "Rev.1",
    workflowSummary: "Approved, unlocked for customer-requested verification evidence, then approved as Rev.1.",
    reportData: reportData({
      reportNumber: "8D-2026-AUTO-001",
      reportType: "customer_8d",
      problemSource: "Customer incoming inspection complaint CAR-26041",
      customerName: "Northstar Automotive Systems",
      priority: "high",
      teamLeader: "Maria Chen, Quality Manager",
      teamMembers: "CNC Process Engineer; Production Supervisor; Metrology Technician; Customer Quality Engineer",
      problemDescription: "The customer found a sharp burr on the oil-channel cross hole of 7 CNC-machined aluminum housings from lot AH-260418. The burr exceeded the agreed visual and tactile acceptance standard and could detach during assembly.",
      whereFound: "Customer incoming inspection, receiving cell 3",
      whenFound: "2026-04-22T09:15",
      whoFound: "Customer incoming inspector",
      productName: "Aluminum valve housing, part VH-4421",
      batchNumber: "AH-260418",
      defectQuantity: "7",
      totalQuantity: "480",
      containmentDescription: "Stopped shipment, quarantined 1,920 pieces across four related lots, introduced 100% borescope inspection, and dispatched certified replacement stock.",
      containmentScope: "Lots AH-260415 through AH-260421, customer stock, finished goods, and WIP after cross-hole operation",
      containmentResponsible: "David Ruiz, Production Quality",
      containmentDueDate: "2026-04-22",
      containmentValidUntil: "Permanent action verified on three consecutive lots",
      containmentVerification: "Two inspectors independently verified the first 300 screened parts; no additional escapes were found.",
      rootCauseOccurrence: "The deburring brush reached end-of-life before the scheduled replacement interval because the actual cross-hole load was higher than the interval study assumed.",
      rootCauseEscape: "Final visual inspection used top lighting only and did not include a borescope angle capable of revealing the cross-hole burr.",
      rootCauseSystem: "Tool-life changes were based on nominal cycle count without a reaction rule for rising burr measurements.",
      fishboneMan: "Operator followed the released work instruction; training records current.",
      fishboneMachine: "Brush wear increased after 8,200 cycles; spindle runout remained within specification.",
      fishboneMaterial: "Material hardness and supplier certificate were within specification.",
      fishboneMethod: "Replacement interval of 10,000 cycles did not reflect the observed wear curve.",
      fishboneMeasurement: "Final inspection method could not consistently see the cross-hole edge.",
      fishboneEnvironment: "Lighting direction contributed to the escape but did not create the burr.",
      why1: "A sharp burr remained because the deburring brush no longer removed the full edge.",
      why2: "The brush was used beyond its effective life for this feature.",
      why3: "The replacement interval was set from nominal cycles rather than measured burr trend.",
      why4: "The control plan had no burr-trend reaction limit.",
      why5: "The process risk review did not connect tool wear data to the control-plan reaction plan.",
      testingPlan: "Measure burr height every 500 cycles on three brushes and verify final inspection detection using seeded defect samples.",
      testingResults: "Burr height rose above 0.08 mm after 8,000 cycles. The revised inspection method detected all 20 seeded samples.",
      confirmedRootCause: "Inadequate brush-life control caused the burr; an insufficient final inspection angle allowed escape.",
      selectedCorrectiveAction: "Set brush replacement at 7,500 cycles, add burr-height reaction limit, and require borescope inspection of the cross hole.",
      correctiveRationale: "The action removes the occurrence mechanism and closes the proven escape point.",
      costEstimate: "$2,400 implementation; expected annual prevention cost below one customer sort.",
      correctiveResponsible: "Lena Park, CNC Process Engineering",
      correctiveTargetDate: "2026-05-03",
      implementationPlan: "Update tool-life counter, control plan, work instruction, inspection fixture, and layered audit checklist.",
      completionDate: "2026-05-03",
      validationMethod: "Three consecutive production lots plus seeded-defect detection challenge.",
      validationResults: "Lots AH-260503, AH-260506, and AH-260509 passed; zero burr defects in 1,440 parts and all seeded defects detected.",
      systemChanges: "PFMEA occurrence and detection controls revised; tool-life reaction rule added.",
      processUpdates: "Control plan and work instruction updated to revision C.",
      horizontalDeployment: "Applied the same tool-life study to six similar cross-hole machining operations.",
      trainingNeeds: "CNC operators and final inspectors trained on revised controls.",
      closureDate: "2026-05-12",
      lessonsLearned: "Tool-life intervals must be supported by measured wear trends and paired with an effective detection method.",
      teamAcknowledgment: "Team and customer quality representative reviewed the evidence package.",
      preparedBy: "Maria Chen",
      preparedDate: "2026-05-10",
      reviewedBy: "David Ruiz",
      reviewedDate: "2026-05-11",
      approverName: "Elena Morris",
      approverDate: "2026-05-12",
    }),
    evidenceFiles: [
      {
        filename: "D2-customer-burr-evidence.jpg",
        stepId: "D2",
        publicPath: "/demo-evidence/automotive-burr-evidence.jpg",
        mimeType: "image/jpeg",
      },
      { filename: "D2-customer-defect-photo-description.txt", stepId: "D2", content: "Photo set documents the sharp cross-hole burr on customer sample 4 of 7 and includes scale reference." },
      { filename: "D4-brush-wear-study.csv", stepId: "D4", content: "cycle_count,burr_height_mm\n7000,0.04\n7500,0.05\n8000,0.07\n8500,0.10\n9000,0.13\n" },
      { filename: "D6-validation-summary.txt", stepId: "D6", content: "Three consecutive lots, 1,440 total pieces, zero burr defects. Seeded defect challenge: 20/20 detected." },
    ],
  },
  molding: {
    slug: "molding",
    title: "Injection Molding 8D - Cosmetic Sink Marks on Customer Housing",
    industry: "Injection molding",
    onlinePath: "/8d-report-example/plastic-injection-molding",
    revision: "Rev.0",
    workflowSummary: "Internal Review completed and report locked after approval.",
    reportData: reportData({
      reportNumber: "8D-2026-MOLD-002",
      reportType: "customer_8d",
      problemSource: "Customer cosmetic inspection complaint",
      customerName: "Arbor Medical Controls",
      priority: "high",
      teamLeader: "Sofia Patel, Quality Engineer",
      teamMembers: "Molding Engineer; Tooling Engineer; Shift Supervisor; Customer Quality",
      problemDescription: "Visible sink marks appeared above two internal ribs on 23 front housings from cavity 2. The defect was visible under the customer's standard 800-lux cosmetic inspection.",
      whereFound: "Customer final assembly cosmetic inspection",
      whenFound: "2026-03-18T14:20",
      whoFound: "Customer quality technician",
      productName: "Controller front housing, part CFH-118",
      batchNumber: "M260316-C2",
      defectQuantity: "23",
      totalQuantity: "1200",
      containmentDescription: "Quarantined cavity-2 output, sorted customer and warehouse stock under 800-lux lighting, and supplied certified cavity-1 replacement stock.",
      containmentScope: "Cavity 2 output produced between March 14 and March 17",
      containmentResponsible: "Andre Lewis, Molding Supervisor",
      containmentDueDate: "2026-03-18",
      containmentValidUntil: "Cavity repair and process validation accepted",
      containmentVerification: "Quality verified the sort standard with the customer defect boundary samples.",
      rootCauseOccurrence: "Cooling restriction near cavity 2 increased local mold temperature, while pack pressure was reduced after an undocumented setup adjustment.",
      rootCauseEscape: "The in-process cosmetic inspection was performed before the part completed post-mold shrinkage.",
      rootCauseSystem: "Setup parameter changes were not electronically locked or independently approved.",
      fishboneMan: "Technician changed pack pressure to address flash without documented approval.",
      fishboneMachine: "Cavity-2 cooling channel flow was 31% below cavity 1.",
      fishboneMaterial: "Resin lot and moisture were within specification.",
      fishboneMethod: "Inspection timing did not account for 30-minute post-mold shrinkage.",
      fishboneMeasurement: "No cooling-flow acceptance check existed after preventive maintenance.",
      fishboneEnvironment: "Inspection lighting met the customer requirement.",
      why1: "Sink marks formed because the rib area did not receive adequate packing during cooling.",
      why2: "Pack pressure was reduced and cavity-2 cooling was restricted.",
      why3: "A setup adjustment was made to control flash and the cooling channel was partially blocked.",
      why4: "Parameter access was not locked and cooling flow was not verified after maintenance.",
      why5: "The control plan did not identify parameter governance and cooling-flow confirmation as critical controls.",
      testingPlan: "DOE comparing pack pressure and cooling flow, followed by 30-minute cosmetic inspection on 300 pieces.",
      testingResults: "Restored cooling flow and approved pack profile eliminated sink marks without reintroducing flash.",
      confirmedRootCause: "Reduced packing combined with restricted cavity-2 cooling caused the defect; premature inspection allowed escape.",
      selectedCorrectiveAction: "Clean and flow-test cooling channel, lock approved recipe, and move cosmetic inspection to 30 minutes after molding.",
      correctiveRationale: "Actions address the validated process causes and the timing-based escape point.",
      correctiveResponsible: "Sofia Patel",
      correctiveTargetDate: "2026-03-27",
      implementationPlan: "Repair cooling circuit, validate recipe, update control plan and inspection standard, train all setup technicians.",
      completionDate: "2026-03-27",
      validationMethod: "Three 400-piece runs from cavity 2 with customer lighting standard.",
      validationResults: "Zero sink marks in 1,200 validated pieces; dimensions and flash remained within limits.",
      systemChanges: "Recipe permissions locked and parameter-change approval added.",
      processUpdates: "Cooling flow check added after mold maintenance.",
      horizontalDeployment: "Reviewed cooling-flow and inspection timing controls on 14 cosmetic housing molds.",
      trainingNeeds: "Setup technicians and inspectors trained on the new approval and inspection timing.",
      closureDate: "2026-04-02",
      lessonsLearned: "Cosmetic acceptance timing must reflect post-mold shrinkage, and recipe changes require governance.",
      teamAcknowledgment: "Quality, molding, tooling, and customer quality approved closure.",
      preparedBy: "Sofia Patel",
      preparedDate: "2026-03-30",
      reviewedBy: "Andre Lewis",
      reviewedDate: "2026-04-01",
      approverName: "Grace Kim",
      approverDate: "2026-04-02",
    }),
    evidenceFiles: [
      {
        filename: "D2-sink-mark-evidence.jpg",
        stepId: "D2",
        publicPath: "/demo-evidence/molding-sink-mark-evidence.jpg",
        mimeType: "image/jpeg",
      },
      { filename: "D2-cosmetic-boundary-sample.txt", stepId: "D2", content: "Boundary sample confirms sink visibility at 800 lux from 45 cm viewing distance." },
      { filename: "D4-cooling-flow-comparison.csv", stepId: "D4", content: "cavity,flow_lpm\n1,8.1\n2_before,5.6\n2_after,8.0\n" },
      { filename: "D6-validation-results.txt", stepId: "D6", content: "Three 400-piece runs completed. Zero sink marks and no dimensional or flash regressions." },
    ],
  },
  electronics: {
    slug: "electronics",
    title: "Electronics 8D - Intermittent LED Module Failure During Burn-In",
    industry: "Electronics manufacturing",
    onlinePath: "/8d-report-example/led-failure",
    revision: "Rev.2",
    workflowSummary: "Submitted to Customer after two evidence revisions; final report locked.",
    reportData: reportData({
      reportNumber: "8D-2026-LED-003",
      reportType: "customer_8d",
      problemSource: "Customer burn-in failure report",
      customerName: "Lumina Industrial Controls",
      priority: "critical",
      teamLeader: "Noah Williams, Electronics Quality Lead",
      teamMembers: "SMT Engineer; Test Engineer; Supplier Quality Engineer; Customer Quality",
      problemDescription: "Nine LED driver modules from lot LD-260501 failed intermittently after 6-14 hours of customer burn-in. Power cycling temporarily restored function.",
      whereFound: "Customer 48-hour burn-in test",
      whenFound: "2026-05-06T11:40",
      whoFound: "Customer reliability technician",
      productName: "LED driver module LDM-24V",
      batchNumber: "LD-260501",
      defectQuantity: "9",
      totalQuantity: "600",
      containmentDescription: "Stopped shipment, quarantined related date codes, screened modules using thermal cycling plus 24-hour burn-in, and issued certified replacements.",
      containmentScope: "Date codes 260428 through 260502 using solder paste lot SP-442",
      containmentResponsible: "Noah Williams",
      containmentDueDate: "2026-05-06",
      containmentValidUntil: "Permanent reflow and verification controls demonstrated",
      containmentVerification: "Screening reproduced all nine known failures and released only passing modules.",
      rootCauseOccurrence: "An unauthorized reflow soak-zone edit reduced wetting margin on connector J4, creating a micro-crack that opened during thermal exposure.",
      rootCauseEscape: "AOI criteria inspected solder area but did not detect the heel-fillet geometry associated with the intermittent joint.",
      rootCauseSystem: "Recipe edit permissions and change review were not restricted to process engineering.",
      fishboneMan: "Technician used shared recipe credentials.",
      fishboneMachine: "Oven calibration was within tolerance; recipe settings were altered.",
      fishboneMaterial: "Paste lot and component plating met specification.",
      fishboneMethod: "Recipe change lacked approval and first-article thermal validation.",
      fishboneMeasurement: "AOI program did not evaluate heel-fillet geometry.",
      fishboneEnvironment: "Customer thermal exposure revealed the latent joint weakness.",
      why1: "The module failed because connector J4 became electrically intermittent.",
      why2: "The solder joint developed a micro-crack during thermal exposure.",
      why3: "The joint had insufficient wetting margin.",
      why4: "The reflow soak-zone recipe was edited below the approved process window.",
      why5: "Shared credentials allowed recipe changes without engineering approval or validation.",
      testingPlan: "Cross-section failed and passing joints, restore approved recipe, update AOI criteria, and run thermal cycle plus 48-hour burn-in.",
      testingResults: "Cross-sections confirmed insufficient heel fillet on failures. Revised process passed 1,800 modules and 60 thermal-cycle samples.",
      confirmedRootCause: "Unauthorized reflow recipe change caused insufficient J4 wetting; incomplete AOI criteria allowed escape.",
      selectedCorrectiveAction: "Restore and password-lock recipe, require engineering change approval, and update AOI heel-fillet criteria.",
      correctiveRationale: "The actions control both the occurrence cause and the verified escape mechanism.",
      correctiveResponsible: "Ava Brooks, SMT Engineering",
      correctiveTargetDate: "2026-05-17",
      implementationPlan: "Lock oven recipes, revise change-control workflow, update AOI program, validate three production lots.",
      completionDate: "2026-05-17",
      validationMethod: "Three production lots, thermal cycling, 48-hour burn-in, and cross-section sampling.",
      validationResults: "1,800 modules passed burn-in; 60 thermal-cycle samples and 12 cross-sections met acceptance criteria.",
      systemChanges: "Recipe permissions restricted and electronic change approval required.",
      processUpdates: "AOI inspection and first-article validation updated.",
      horizontalDeployment: "Audited recipe access and AOI criteria on all six SMT lines.",
      trainingNeeds: "SMT technicians and process engineers trained on revised change control.",
      closureDate: "2026-05-24",
      lessonsLearned: "Shared process credentials create uncontrolled changes; detection criteria must target the actual failure geometry.",
      teamAcknowledgment: "Customer accepted Rev.2 evidence package and closure recommendation.",
      preparedBy: "Noah Williams",
      preparedDate: "2026-05-21",
      reviewedBy: "Ava Brooks",
      reviewedDate: "2026-05-22",
      approverName: "Priya Raman",
      approverDate: "2026-05-24",
    }),
    evidenceFiles: [
      {
        filename: "D4-led-joint-inspection.jpg",
        stepId: "D4",
        publicPath: "/demo-evidence/electronics-led-evidence.jpg",
        mimeType: "image/jpeg",
      },
      { filename: "D2-burn-in-failure-log.csv", stepId: "D2", content: "serial,failure_hour,recovery_after_power_cycle\nLDM-041,6,yes\nLDM-118,11,yes\nLDM-204,14,yes\n" },
      { filename: "D4-cross-section-findings.txt", stepId: "D4", content: "Failed J4 joints showed incomplete heel fillet and micro-crack initiation. Passing controls met the approved geometry." },
      { filename: "D6-reliability-validation.txt", stepId: "D6", content: "1,800 modules passed 48-hour burn-in. Sixty modules passed thermal cycling. Twelve cross-sections met acceptance criteria." },
    ],
  },
};

export function getDemoReport(type: string): DemoReport {
  return DEMO_REPORTS[type] || DEMO_REPORTS.automotive;
}
