import { NextRequest, NextResponse } from "next/server";
import { jsPDF } from "jspdf";
import JSZip from "jszip";
import { getDemoReport } from "@/lib/demo-reports";
import { generateWordDocument } from "@/lib/word-export";

async function createPdf(type: string, origin: string) {
  const sample = getDemoReport(type);
  const data = sample.reportData;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  let y = 22;
  const addSection = (label: string, value: string) => {
    if (y > 265) {
      doc.addPage();
      y = 22;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(79, 70, 229);
    doc.text(label, 18, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(35, 35, 35);
    const lines = doc.splitTextToSize(value || "-", 174);
    doc.text(lines, 18, y);
    y += lines.length * 4.5 + 6;
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(79, 70, 229);
  doc.text("CUSTOMER-READY 8D DEMO", 18, y);
  y += 12;
  doc.setTextColor(20, 20, 20);
  doc.setFontSize(13);
  doc.text(doc.splitTextToSize(sample.title, 174), 18, y);
  y += 16;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`${data.reportNumber}  |  ${sample.revision}  |  ${sample.industry}`, 18, y);
  y += 8;
  doc.text(sample.workflowSummary, 18, y, { maxWidth: 174 });
  y += 14;
  const rows = [
    ["Customer / Product / Lot", `${data.customerName} / ${data.productName} / ${data.batchNumber}`],
    ["D1 Team", `${data.teamLeader}; ${data.teamMembers}`],
    ["D2 Problem Description", data.problemDescription],
    ["D3 Containment", data.containmentDescription],
    ["D4 Occurrence Cause", data.rootCauseOccurrence],
    ["D4 Escape Cause", data.rootCauseEscape],
    ["D4 Confirmed Root Cause", data.confirmedRootCause],
    ["D4 5-Why", [data.why1, data.why2, data.why3, data.why4, data.why5].map((v, i) => `${i + 1}. ${v}`).join("\n")],
    ["D5 Corrective Action", data.selectedCorrectiveAction],
    ["D6 Verification", `${data.validationMethod}\n${data.validationResults}`],
    ["D7 Prevention", `${data.systemChanges}\n${data.horizontalDeployment}`],
    ["D8 Approval", `Prepared: ${data.preparedBy} (${data.preparedDate})\nReviewed: ${data.reviewedBy} (${data.reviewedDate})\nApproved: ${data.approverName} (${data.approverDate})`],
    ["Attachment List", sample.evidenceFiles.map((file) => `${file.stepId}: ${file.filename}`).join("\n")],
  ];
  for (const [label, value] of rows) {
    addSection(label, value);
  }
  for (const file of sample.evidenceFiles.filter((item) => item.publicPath)) {
    if (y > 205) {
      doc.addPage();
      y = 22;
    }
    addSection(`${file.stepId} Image Evidence`, file.filename);
    try {
      const response = await fetch(new URL(file.publicPath!, origin));
      if (response.ok) {
        const image = new Uint8Array(await response.arrayBuffer());
        doc.addImage(image, "JPEG", 18, y, 174, 116);
        y += 124;
      }
    } catch {
      addSection("Image status", "Image evidence could not be embedded in this generated sample.");
    }
  }
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text("Demonstration report generated by 8D Reports. Evidence is illustrative and must not be used as real production evidence.", 18, 287);
  return Buffer.from(doc.output("arraybuffer"));
}

export async function GET(req: NextRequest, { params }: { params: Promise<{ type: string }> }) {
  const { type } = await params;
  const sample = getDemoReport(type);
  const format = req.nextUrl.searchParams.get("format") || "pdf";
  const baseFilename = `${sample.slug}-8d-demo`;

  if (format === "docx") {
    const buffer = await generateWordDocument({
      reportData: sample.reportData,
      reportTitle: sample.title,
      reportId: sample.reportData.reportNumber,
      withWatermark: false,
      locale: "en",
      attachmentImages: sample.evidenceFiles.map((file) => ({
        url: file.publicPath ? new URL(file.publicPath, req.nextUrl.origin).toString() : "",
        filename: file.filename,
        stepId: file.stepId,
        mimeType: file.mimeType || (file.filename.endsWith(".csv") ? "text/csv" : "text/plain"),
      })),
    });
    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="${baseFilename}.docx"`,
      },
    });
  }

  if (format === "zip") {
    const zip = new JSZip();
    const pdf = await createPdf(type, req.nextUrl.origin);
    const word = await generateWordDocument({
      reportData: sample.reportData,
      reportTitle: sample.title,
      reportId: sample.reportData.reportNumber,
      withWatermark: false,
      locale: "en",
      attachmentImages: sample.evidenceFiles.map((file) => ({
        url: file.publicPath ? new URL(file.publicPath, req.nextUrl.origin).toString() : "",
        filename: file.filename,
        stepId: file.stepId,
        mimeType: file.mimeType || (file.filename.endsWith(".csv") ? "text/csv" : "text/plain"),
      })),
    });
    zip.file(`${baseFilename}.pdf`, pdf);
    zip.file(`${baseFilename}.docx`, word);
    const evidence = zip.folder("attachments");
    for (const file of sample.evidenceFiles) {
      if (file.publicPath) {
        const response = await fetch(new URL(file.publicPath, req.nextUrl.origin));
        if (response.ok) evidence?.file(file.filename, await response.arrayBuffer());
      } else {
        evidence?.file(file.filename, file.content || "");
      }
    }
    evidence?.file("README.txt", "These files demonstrate how non-image evidence is preserved in a customer delivery ZIP package.");
    const buffer = await zip.generateAsync({ type: "nodebuffer" });
    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${baseFilename}-delivery-package.zip"`,
      },
    });
  }

  const bytes = await createPdf(type, req.nextUrl.origin);
  return new NextResponse(new Uint8Array(bytes), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${baseFilename}.pdf"`,
    },
  });
}
