import type { SocialKnowledgeEntry } from "./types"

export const socialAccountKnowledgeBase: SocialKnowledgeEntry[] = [
  {
    id: "platform_twitter_x",
    category: "platform_specs",
    title: "Twitter/X 平台运营规范",
    description: "Twitter/X 是实时信息流为核心的公共对话平台，适合舆情监控、竞品追踪和行业趋势追踪。算法偏好高互动率内容。",
    platforms: ["twitter_x"],
    targetRegions: ["global"],
    keyConcepts: ["280字符限制", "Threads链式发布", "实时搜索", "社区笔记", "付费API v2"],
    practicalGuidance: "发布频率建议每天3-5条，最佳发布时间为工作日上午9-11点和下午2-4点。使用2-3个精准话题标签，避免过度使用。",
    relatedEntries: ["listening_brand_monitoring", "content_short_form"],
    tags: ["twitter", "x", "实时", "短内容", "舆情"],
  },
  {
    id: "platform_instagram",
    category: "platform_specs",
    title: "Instagram 视觉优先运营策略",
    description: "Instagram 以视觉内容为核心，Reels算法优先，Stories适合日常互动。理想用于品牌视觉展示和生活方式营销。",
    platforms: ["instagram"],
    targetRegions: ["global"],
    keyConcepts: ["Reels优先算法", "Stories互动", "视觉一致性", "Grid布局", "Shopping标签"],
    practicalGuidance: "Reels建议15-30秒，竖屏9:16比例。Stories每天3-5条保持活跃度。Feed帖子每周3-5条保持质量优先。",
    relatedEntries: ["account_visual_design", "content_visual_branding"],
    tags: ["instagram", "视觉", "reels", "stories", "品牌展示"],
  },
  {
    id: "platform_linkedin",
    category: "platform_specs",
    title: "LinkedIn B2B专业内容策略",
    description: "LinkedIn 是职业社交网络，适合B2B营销、行业思想领导力和人才招聘。长文和文档分享效果最佳。",
    platforms: ["linkedin"],
    targetRegions: ["global"],
    keyConcepts: ["职业社交图谱", "长文内容", "文档分享", "公司主页", "员工倡导"],
    practicalGuidance: "公司主页每周3-5篇内容，员工个人账号参与互动可扩大3-5倍触达。长文(1000-2000字)获得最高互动。",
    relatedEntries: ["content_b2b_strategy", "intelligence_industry_trends"],
    tags: ["linkedin", "B2B", "专业内容", "思想领导力", "长文"],
  },
  {
    id: "platform_tiktok",
    category: "platform_specs",
    title: "TikTok 短视频算法机制",
    description: "TikTok 以算法推荐为核心，内容本身质量决定分发。适合品牌年轻化、病毒传播和创意营销。",
    platforms: ["tiktok"],
    targetRegions: ["global"],
    keyConcepts: ["For You Page算法", "声音驱动", "趋势参与", "Duet/Stitch", "直播带货"],
    practicalGuidance: "前3秒是钩子黄金时间。使用平台热门音效和趋势标签。每天发布1-3条，保持内容新鲜度。",
    relatedEntries: ["content_short_video", "idea_validation_content_test"],
    tags: ["tiktok", "短视频", "算法推荐", "病毒传播", "年轻化"],
  },
  {
    id: "platform_reddit",
    category: "platform_specs",
    title: "Reddit 社区验证最佳实践",
    description: "Reddit 是匿名兴趣社区，投票机制决定内容可见度。适合获取用户真实反馈、早期市场信号和社区验证。",
    platforms: ["reddit"],
    targetRegions: ["global"],
    keyConcepts: ["Subreddit社区", "Karma机制", "AMAs", "Upvote/Downvote", "社区规则"],
    practicalGuidance: "先潜伏(潜水)1-2周了解社区文化后再参与。提供真实价值，避免硬推销。每个Subreddit有独立规则必须遵守。",
    relatedEntries: ["idea_validation_community", "intelligence_user_insights"],
    tags: ["reddit", "社区", "验证", "用户反馈", "匿名"],
  },
  {
    id: "platform_weibo",
    category: "platform_specs",
    title: "微博实时舆情与品牌声量运营",
    description: "微博是中国公开社交广场，热搜机制驱动内容分发。适合舆情监控、品牌声量建设、事件营销和明星/KOL合作。",
    platforms: ["weibo"],
    targetRegions: ["cn"],
    keyConcepts: ["热搜榜", "话题广场", "超话社区", "蓝V认证", "粉丝头条", "微博故事"],
    practicalGuidance: "每天发布3-5条，蹭热搜话题可获额外曝光。蓝V认证提升信任度。微博抽奖是快速涨粉的有效手段。",
    relatedEntries: ["listening_brand_monitoring", "content_hotspot_hijack"],
    tags: ["微博", "热搜", "舆情", "品牌声量", "中国"],
  },
  {
    id: "platform_xiaohongshu",
    category: "platform_specs",
    title: "小红书种草与消费决策平台",
    description: "小红书是图文种草+短视频的消费决策平台，女性用户为主，消费力强。适合产品种草、口碑营销和消费趋势洞察。",
    platforms: ["xiaohongshu"],
    targetRegions: ["cn"],
    keyConcepts: ["笔记种草", "商品笔记", "薯条推广", "品牌号", "蒲公英平台", "好物体验"],
    practicalGuidance: "图文笔记标题需包含关键词(SEO导向)。封面图精美是流量关键。真实体验分享比硬广效果好10倍。",
    relatedEntries: ["idea_validation_content_test", "intelligence_user_insights"],
    tags: ["小红书", "种草", "消费决策", "女性用户", "中国"],
  },
  {
    id: "platform_douyin",
    category: "platform_specs",
    title: "抖音兴趣电商与品牌破圈",
    description: "抖音以算法推荐为核心，短视频+直播+团购形成完整电商闭环。适合品牌破圈、挑战赛和直播电商。",
    platforms: ["douyin"],
    targetRegions: ["cn"],
    keyConcepts: ["推荐算法", "DOU+推广", "挑战赛", "直播电商", "团购", "企业号"],
    practicalGuidance: "完播率和互动率是核心算法指标。每天发布1-2条保证质量。直播前发布预热视频可提升直播间流量30-50%。",
    relatedEntries: ["content_short_video", "content_live_streaming"],
    tags: ["抖音", "算法推荐", "直播电商", "挑战赛", "中国"],
  },
  {
    id: "platform_zhihu",
    category: "platform_specs",
    title: "知乎专业内容与SEO长尾策略",
    description: "知乎是高学历理性用户的问答社区，内容在搜索引擎中有高权重。适合专业背书、行业洞察和SEO长尾流量。",
    platforms: ["zhihu"],
    targetRegions: ["cn"],
    keyConcepts: ["问答机制", "盐选专栏", "知乎Live", "专业认证", "长尾搜索", "想法"],
    practicalGuidance: "回答质量重于数量，深度回答可获持续流量。问题选择要关注SEO搜索量和竞争度。专业认证增加答案权重。",
    relatedEntries: ["intelligence_industry_trends", "content_long_form"],
    tags: ["知乎", "问答", "专业背书", "SEO", "中国"],
  },
  {
    id: "account_creation_checklist",
    category: "account_management",
    title: "社交账户创建完整清单",
    description: "从零开始在任意平台创建品牌社交账户的完整步骤指南，确保账户资料完整、品牌一致、安全可靠。",
    platforms: ["twitter_x", "facebook", "instagram", "linkedin", "tiktok", "weibo", "xiaohongshu", "douyin"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["平台选择", "用户名策略", "视觉一致性", "安全设置", "认证申请"],
    practicalGuidance: "1) 检查用户名在所有目标平台的可用性 2) 使用品牌邮箱注册 3) 开启二步验证 4) 完成所有资料字段 5) 发布3-5条启动内容后再开始推广。",
    relatedEntries: ["account_visual_design", "account_security"],
    tags: ["账户创建", "清单", "启动", "品牌", "安全"],
  },
  {
    id: "account_visual_design",
    category: "account_management",
    title: "社交账户视觉统一设计",
    description: "确保品牌在多个社交平台的视觉呈现保持一致，同时适配各平台的具体规范。需要美术专家深度协同。",
    platforms: ["twitter_x", "facebook", "instagram", "linkedin", "tiktok", "youtube", "weibo", "xiaohongshu", "douyin"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["头像适配", "封面图设计", "品牌色彩一致", "字体识别", "模板化设计"],
    practicalGuidance: "头像建议使用Logo简化版，确保在小尺寸(48x48px)下清晰。各平台封面图尺寸不同(Twitter:1500x500, LinkedIn:1584x396, 微博:920x300)。需与美术专家协同出图。",
    relatedEntries: ["account_creation_checklist", "content_visual_branding"],
    tags: ["视觉设计", "品牌一致性", "头像", "封面图", "协同美术专家"],
  },
  {
    id: "account_security",
    category: "account_management",
    title: "社交账户安全最佳实践",
    description: "保护社交账户不被盗用、限制或封禁的安全措施，包括密码管理、权限控制和异常监控。",
    platforms: ["twitter_x", "facebook", "instagram", "linkedin", "tiktok", "youtube", "weibo", "xiaohongshu", "douyin"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["二步验证", "强密码策略", "权限分级", "异常登录检测", "API密钥安全"],
    practicalGuidance: "所有账户必须开启二步验证(2FA)。使用密码管理器生成和存储密码。API密钥定期轮换(每90天)。建立账户异常登录即时告警机制。",
    relatedEntries: ["issue_account_security", "automation_api_management"],
    tags: ["安全", "二步验证", "密码", "权限", "账户保护"],
  },
  {
    id: "content_short_form",
    category: "content_strategy",
    title: "短内容创作策略",
    description: "针对Twitter/X、Threads、微博等短文本平台的创作方法论，包括文案结构、话题标签和发布时间优化。",
    platforms: ["twitter_x", "threads", "weibo", "jike"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["钩子开头", "信息层级", "CTA引导", "话题标签策略", "发布时间优化"],
    practicalGuidance: "前20个字符决定用户是否继续阅读。使用数字和对比制造信息张力。每条内容必须有明确的CTA(评论/转发/点击)。",
    relatedEntries: ["content_calendar", "platform_twitter_x", "platform_weibo"],
    tags: ["短内容", "文案", "钩子", "话题标签", "CTA"],
  },
  {
    id: "content_long_form",
    category: "content_strategy",
    title: "长内容深度创作策略",
    description: "针对LinkedIn、微信公众号、知乎等长内容平台的创作方法论，包括结构化写作和SEO优化。",
    platforms: ["linkedin", "wechat", "zhihu"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["结构化写作", "金字塔原理", "SEO优化", "视觉断点", "分享诱因"],
    practicalGuidance: "使用H2/H3标题分割内容提升可读性。每300-500字插入图片/引用作为视觉断点。在微信公众号需注意排版美学。",
    relatedEntries: ["platform_linkedin", "platform_zhihu", "content_calendar"],
    tags: ["长内容", "深度写作", "SEO", "结构化", "排版"],
  },
  {
    id: "content_short_video",
    category: "content_strategy",
    title: "短视频内容创作方法论",
    description: "针对TikTok、抖音、Reels等短视频平台的创作策略，包括钩子设计、节奏控制和趋势借力。",
    platforms: ["tiktok", "douyin", "instagram"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["3秒钩子", "节奏控制", "声音驱动", "趋势借力", "完播率优化"],
    practicalGuidance: "前3秒必须有强钩子(问题/悬念/视觉冲击/情感触动)。使用平台热门音效。视频长度控制在15-60秒为佳。字幕必须清晰(很多人静音观看)。",
    relatedEntries: ["platform_tiktok", "platform_douyin", "content_hotspot_hijack"],
    tags: ["短视频", "钩子", "音效", "完播率", "节奏"],
  },
  {
    id: "content_calendar",
    category: "content_strategy",
    title: "内容日历规划体系",
    description: "建立日/周/月的内容发布日历，确保内容产出稳定、主题多元、与品牌节奏同步。",
    platforms: ["twitter_x", "facebook", "instagram", "linkedin", "tiktok", "weibo", "xiaohongshu", "douyin"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["发布频率", "内容主题配比", "热点日历", "内容复用", "质量vs数量平衡"],
    practicalGuidance: "内容主题建议按5:3:2配比(50%品牌价值内容+30%行业洞察+20%用户互动)。提前一周排好下周内容。预留20%弹性空间应对热点。",
    relatedEntries: ["content_short_form", "content_long_form", "content_hotspot_hijack"],
    tags: ["内容日历", "规划", "发布频率", "主题配比", "素材库"],
  },
  {
    id: "content_hotspot_hijack",
    category: "content_strategy",
    title: "热点借势营销策略",
    description: "快速识别和借势热点话题的方法论，包括热点监控机制、响应流程和风险控制。",
    platforms: ["twitter_x", "tiktok", "weibo", "douyin"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["热点监控", "快速响应", "品牌关联度", "风险判断", "内容模版化"],
    practicalGuidance: "建立热点监控关键词库和自动提醒。热点出现后2小时是黄金响应窗口。不是所有热点都适合借势——需评估品牌关联度和潜在风险。",
    relatedEntries: ["listening_trend_tracking", "crisis_avoidance"],
    tags: ["热点借势", "实时营销", "快速响应", "风险评估", "趋势"],
  },
  {
    id: "listening_brand_monitoring",
    category: "social_listening",
    title: "品牌社交监听体系",
    description: "建立品牌在社交平台的全方位监听机制，追踪品牌提及、情感趋势和影响力声量。",
    platforms: ["twitter_x", "facebook", "instagram", "reddit", "weibo", "xiaohongshu", "douyin", "zhihu"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["品牌关键词", "情感分析", "声量份额", "影响力追踪", "告警机制"],
    practicalGuidance: "监控关键词至少包含:品牌名+别名+产品名+创始人名+品牌Campaign标签。每周输出情感趋势报告。设置负面提及突增告警(1小时内负面翻倍即为预警信号)。",
    relatedEntries: ["listening_competitive", "crisis_early_warning"],
    tags: ["品牌监控", "情感分析", "声量", "告警", "社交监听"],
  },
  {
    id: "listening_competitive",
    category: "social_listening",
    title: "竞品社交情报收集",
    description: "系统化收集和分析竞品在社交平台上的策略、表现和用户反馈，为自身策略优化提供数据支撑。",
    platforms: ["twitter_x", "instagram", "linkedin", "tiktok", "weibo", "xiaohongshu", "douyin"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["竞品识别", "内容策略对标", "互动率对比", "Campaign追踪", "用户反馈提炼"],
    practicalGuidance: "追踪竞品发布频率、内容类型、互动表现，纵向对比其内容策略演变。重点关注竞品用户的投诉和不满——这是我们的机会点。",
    relatedEntries: ["listening_brand_monitoring", "intelligence_competitive_analysis"],
    tags: ["竞品分析", "社交情报", "对标", "策略", "机会发现"],
  },
  {
    id: "listening_trend_tracking",
    category: "social_listening",
    title: "行业趋势社交追踪",
    description: "利用社交平台追踪行业趋势信号的方法论，包括关键词策略、趋势信号识别和趋势验证。",
    platforms: ["twitter_x", "reddit", "linkedin", "tiktok", "weibo", "zhihu"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["趋势关键词", "信号识别", "早期采纳者追踪", "跨平台验证", "Gartner Hype Cycle"],
    practicalGuidance: "关注行业KOL的早期讨论、技术会议的话题标签、学术论文的社交讨论。跨平台一致性是趋势真实性信号。使用Google Trends辅助验证。",
    relatedEntries: ["intelligence_industry_trends", "listening_brand_monitoring"],
    tags: ["趋势追踪", "行业洞察", "信号识别", "早期信号", "跨平台"],
  },
  {
    id: "intelligence_user_insights",
    category: "social_listening",
    title: "用户社交洞察挖掘",
    description: "从社交平台的用户自发讨论中挖掘深层用户需求、痛点和行为模式。与数据分析专家和产品专家高度协同。",
    platforms: ["twitter_x", "reddit", "xiaohongshu", "zhihu", "douyin"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["需求识别", "痛点提取", "语言模式", "消费决策路径", "未满足需求"],
    practicalGuidance: "重点关注用户用'我希望...''为什么没有...''要是能有...'等句式表达的内容——这是未满足需求的直接信号。定期做用户讨论主题聚类分析。",
    relatedEntries: ["idea_validation_community", "listening_brand_monitoring"],
    tags: ["用户洞察", "需求挖掘", "痛点", "消费者行为", "社交数据"],
  },
  {
    id: "intelligence_competitive_analysis",
    category: "social_listening",
    title: "竞品社交深度分析",
    description: "超越基础监听，进行竞品的社交策略、用户群体、内容效率和品牌定位的深度分析。需与营销专家和数据分析专家协同。",
    platforms: ["twitter_x", "instagram", "linkedin", "tiktok", "weibo", "xiaohongshu"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["内容效率分析", "用户群体分析", "品牌定位对比", "Campaign拆解", "KOL矩阵分析"],
    practicalGuidance: "分析竞品内容表现TOP/BOTTOM，提炼其成功模式。追踪竞品合作的KOL，评估其影响力矩阵。对比自身与竞品在关键话题上的声量份额。",
    relatedEntries: ["listening_competitive", "intelligence_user_insights"],
    tags: ["竞品深度分析", "策略拆解", "内容效率", "KOL矩阵", "定位对比"],
  },
  {
    id: "idea_validation_content_test",
    category: "idea_validation",
    title: "社交内容概念验证",
    description: "通过发布概念性内容在社交平台测试商业想法的市场需求。最低成本的市场验证方式之一。需与想法验证专家深度协同。",
    platforms: ["twitter_x", "instagram", "tiktok", "xiaohongshu", "douyin"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["概念内容", "假说驱动", "互动信号解读", "A/B测试", "快速迭代"],
    practicalGuidance: "发布产品概念图/功能描述/用户故事等内容形式。追踪互动率(目标>行业均值2倍)、正向评论比例(>70%)和用户自发问题数量(>10个)。3天内数据低于阈值则调整方向。",
    relatedEntries: ["idea_validation_community", "idea_validation_landing_page"],
    tags: ["概念验证", "内容测试", "市场需求", "互动信号", "低成本验证"],
  },
  {
    id: "idea_validation_community",
    category: "idea_validation",
    title: "社区讨论验证法",
    description: "在Reddit、知乎、豆瓣等社区发起讨论来验证商业假设。利用社区投票机制识别强信号。",
    platforms: ["reddit", "zhihu"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["社区讨论发起", "投票分析", "评论质量评估", "信号强度分级", "早期用户识别"],
    practicalGuidance: "以'寻求建议/讨论'而非推销的口吻发起。关注讨论深度(长篇回复数)和质量而非单纯数量。识别出愿意深入讨论的用户可作为种子用户。",
    relatedEntries: ["idea_validation_content_test", "platform_reddit", "platform_zhihu"],
    tags: ["社区验证", "讨论法", "投票分析", "种子用户", "深度反馈"],
  },
  {
    id: "idea_validation_landing_page",
    category: "idea_validation",
    title: "社交引流Landing Page验证",
    description: "创建Landing Page并通过社交广告和内容引流来验证商业假设。需要更完整的技术支撑。需协同编程专家和本地操作专家。",
    platforms: ["twitter_x", "facebook", "instagram", "linkedin", "tiktok", "weibo", "xiaohongshu"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["Landing Page", "社交广告", "转化追踪", "A/B测试", "获客成本计算"],
    practicalGuidance: "Landing Page核心元素:价值主张+功能亮点+社交证明+注册CTA。社交广告小额测试(预算$50-200/平台)。核心指标:注册率>5%、CTR>2%、CAC<目标值。",
    relatedEntries: ["idea_validation_content_test", "content_calendar"],
    tags: ["Landing Page", "社交广告", "转化率", "A/B测试", "获客成本"],
  },
  {
    id: "crisis_early_warning",
    category: "crisis_management",
    title: "舆情危机早期预警机制",
    description: "建立社交舆情危机的早期发现和预警体系，确保在危机爆发前或初期就被识别和处理。",
    platforms: ["twitter_x", "facebook", "weibo", "xiaohongshu", "douyin"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["负面信号识别", "传播速度监控", "情感突变检测", "告警阈值", "升级流程"],
    practicalGuidance: "设定3级告警机制: 1)负面提及单日增幅>50%→黄色预警 2)负面提及超过正面→橙色预警 3)出现主流媒体报道/KOL转发→红色预警立即上报客户需求专家。",
    relatedEntries: ["crisis_response", "listening_brand_monitoring", "issue_reporting_process"],
    tags: ["危机预警", "负面监控", "告警机制", "情感突变", "升级流程"],
  },
  {
    id: "crisis_response",
    category: "crisis_management",
    title: "社交舆情危机响应策略",
    description: "当舆情危机发生时，标准的响应流程和策略，包括对外沟通、对内协调和恢复计划。",
    platforms: ["twitter_x", "facebook", "weibo", "xiaohongshu", "douyin"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["黄金响应时间", "声明模板", "发言人制度", "多平台一致性", "后续跟进"],
    practicalGuidance: "黄金响应窗口：社交媒体危机发生后1-4小时内必须发布初步声明。声明三要素:承认+行动+承诺。不要删除负面评论(会引发更大反弹)。所有平台同步发布声明。",
    relatedEntries: ["crisis_early_warning", "issue_reporting_process"],
    tags: ["危机响应", "公关", "声明", "舆论", "恢复"],
  },
  {
    id: "issue_reporting_process",
    category: "crisis_management",
    title: "问题上报与协作解决流程",
    description: "定义当社交运营遇到问题时的标准化上报流程和跨专家协作机制。确保问题不遗漏、响应及时、解决有效。",
    platforms: ["twitter_x", "facebook", "instagram", "linkedin", "tiktok", "youtube", "weibo", "xiaohongshu", "douyin", "zhihu"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["问题分级", "上报路由", "协作矩阵", "SLA时限", "闭环跟踪"],
    practicalGuidance: "严重(critical)问题立即上报客户需求专家并同步所有相关方。重要(major)问题2小时内上报对应专家。一般(minor)问题48小时内上报。建立Issue Tracking确保闭环。",
    relatedEntries: ["crisis_early_warning", "crisis_response", "account_security"],
    tags: ["问题上报", "协作", "SLA", "闭环", "跨专家"],
  },
  {
    id: "automation_publishing",
    category: "automation",
    title: "自动化发布系统搭建",
    description: "搭建跨平台的定时发布和内容管理自动化系统。需与编程专家和本地操作专家深度协同。",
    platforms: ["twitter_x", "facebook", "instagram", "linkedin", "tiktok", "weibo"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["定时发布", "内容队列", "多平台适配", "API对接", "发布状态追踪"],
    practicalGuidance: "选择稳定的第三方工具或自建发布系统。优先对接官方API而非网页自动化(更稳定安全)。建立发布前人工审核环节。每个平台配置独立的API密钥。",
    relatedEntries: ["automation_monitoring", "account_security"],
    tags: ["自动化", "定时发布", "API", "多平台", "内容队列"],
  },
  {
    id: "automation_monitoring",
    category: "automation",
    title: "自动化社交监控系统",
    description: "搭建自动化的社交监听和舆情监控系统，实现7x24小时持续监控和智能告警。需协同本地操作专家。",
    platforms: ["twitter_x", "facebook", "instagram", "reddit", "weibo", "xiaohongshu", "douyin", "zhihu"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["关键词监控", "实时数据流", "情感自动分析", "异常检测", "定时报告"],
    practicalGuidance: "使用平台Streaming API或定时轮询。监控频率:实时(关键品牌词) + 每小时(竞品词) + 每天(行业词)。异常检测使用统计学方法(3-sigma rule)。",
    relatedEntries: ["automation_publishing", "listening_brand_monitoring", "crisis_early_warning"],
    tags: ["自动化监控", "实时", "情感分析", "异常检测", "7x24"],
  },
  {
    id: "best_practice_engagement",
    category: "best_practice",
    title: "社交互动最佳实践",
    description: "提升社交平台用户互动率和社区健康度的最佳实践指南。",
    platforms: ["twitter_x", "facebook", "instagram", "linkedin", "tiktok", "weibo", "xiaohongshu"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["回复速度", "个性化回应", "UGC鼓励", "社区培育", "负面处理"],
    practicalGuidance: "工作日1小时内回复评论私信，节假日4小时内。回复要个性化，避免机械模板。主动点赞和转发高质量UGC。负面反馈先共情再解决，公开转私密处理。",
    relatedEntries: ["content_calendar", "listening_brand_monitoring"],
    tags: ["互动", "回复速度", "UGC", "社区", "负面处理"],
  },
  {
    id: "best_practice_cross_platform",
    category: "best_practice",
    title: "跨平台社交运营协同",
    description: "管理多平台社交矩阵时的协同策略，确保品牌一致性的同时最大化各平台特性。",
    platforms: ["twitter_x", "facebook", "instagram", "linkedin", "tiktok", "youtube", "weibo", "xiaohongshu", "douyin", "zhihu"],
    targetRegions: ["global", "cn"],
    keyConcepts: ["品牌一致性", "平台差异化", "内容复用", "跨平台联动", "资源分配"],
    practicalGuidance: "核心理念：一次创作，多平台适配分发，而非简单复制粘贴。内容主轴统一，表达形式根据平台特色调整。跨平台Campaign需设计平台间的流量互导机制。",
    relatedEntries: ["content_calendar", "automation_publishing", "account_visual_design"],
    tags: ["跨平台", "协同", "内容复用", "平台差异化", "品牌一致性"],
  },
]

export const issueEscalationMatrix: Record<string, { targets: string[]; notify: string[]; urgency: string }> = {
  account_security: {
    targets: ["programming_expert", "customer_requirements_expert"],
    notify: ["project_manager"],
    urgency: "immediate",
  },
  content_compliance: {
    targets: ["customer_requirements_expert"],
    notify: ["marketing_expert"],
    urgency: "within_hour",
  },
  public_sentiment_crisis: {
    targets: ["customer_requirements_expert", "marketing_expert", "quality_expert"],
    notify: ["project_manager"],
    urgency: "immediate",
  },
  api_technical: {
    targets: ["programming_expert", "local_operations_expert"],
    notify: ["project_manager"],
    urgency: "within_hour",
  },
  content_strategy: {
    targets: ["marketing_expert"],
    notify: [],
    urgency: "within_day",
  },
  data_anomaly: {
    targets: ["data_analysis_expert", "data_calibration_expert"],
    notify: [],
    urgency: "within_day",
  },
  platform_policy: {
    targets: ["customer_requirements_expert", "marketing_expert"],
    notify: ["project_manager"],
    urgency: "within_day",
  },
  resource_shortage: {
    targets: ["project_manager", "cost_expert"],
    notify: ["customer_requirements_expert"],
    urgency: "within_day",
  },
}

export const platformSpecs: Record<string, {
  name: string
  maxChars: number
  bestPostingTimes: string[]
  idealFrequency: string
  imageSizes: Record<string, string>
  region: "global" | "cn"
}> = {
  twitter_x: {
    name: "Twitter/X",
    maxChars: 280,
    bestPostingTimes: ["工作日 9:00-11:00", "工作日 14:00-16:00"],
    idealFrequency: "3-5条/天",
    imageSizes: { post: "1200x675", header: "1500x500", avatar: "400x400" },
    region: "global",
  },
  instagram: {
    name: "Instagram",
    maxChars: 2200,
    bestPostingTimes: ["周二-周四 10:00-14:00", "周五 16:00-20:00"],
    idealFrequency: "Feed:3-5条/周, Stories:3-5条/天, Reels:3-7条/周",
    imageSizes: { feed_square: "1080x1080", feed_portrait: "1080x1350", story: "1080x1920", reels: "1080x1920" },
    region: "global",
  },
  linkedin: {
    name: "LinkedIn",
    maxChars: 3000,
    bestPostingTimes: ["周二-周四 8:00-10:00", "周二-周四 12:00-13:00"],
    idealFrequency: "3-5条/周",
    imageSizes: { post: "1200x627", header: "1584x396", avatar: "400x400" },
    region: "global",
  },
  tiktok: {
    name: "TikTok",
    maxChars: 2200,
    bestPostingTimes: ["每天 6:00-10:00", "每天 19:00-23:00"],
    idealFrequency: "1-3条/天",
    imageSizes: { video: "1080x1920", avatar: "200x200" },
    region: "global",
  },
  reddit: {
    name: "Reddit",
    maxChars: 40000,
    bestPostingTimes: ["周一-周五 6:00-8:00 EST"],
    idealFrequency: "取决于Subreddit规则",
    imageSizes: { post: "1200x628", avatar: "256x256" },
    region: "global",
  },
  weibo: {
    name: "微博",
    maxChars: 2000,
    bestPostingTimes: ["每天 8:00-10:00", "每天 12:00-14:00", "每天 20:00-23:00"],
    idealFrequency: "3-5条/天",
    imageSizes: { post: "1200x800", cover: "920x300", avatar: "200x200" },
    region: "cn",
  },
  xiaohongshu: {
    name: "小红书",
    maxChars: 1000,
    bestPostingTimes: ["每天 7:00-9:00", "每天 12:00-14:00", "每天 18:00-22:00"],
    idealFrequency: "1-3条/天",
    imageSizes: { note: "1080x1440", cover: "1080x1440", avatar: "400x400" },
    region: "cn",
  },
  douyin: {
    name: "抖音",
    maxChars: 2000,
    bestPostingTimes: ["每天 7:00-9:00", "每天 12:00-13:00", "每天 18:00-22:00"],
    idealFrequency: "1-2条/天",
    imageSizes: { video: "1080x1920", avatar: "200x200" },
    region: "cn",
  },
  zhihu: {
    name: "知乎",
    maxChars: 100000,
    bestPostingTimes: ["工作日 12:00-14:00", "工作日 21:00-23:00", "周末 10:00-12:00"],
    idealFrequency: "3-5条回答/周 + 1-2篇文章/周",
    imageSizes: { article: "1920x1080", avatar: "400x400" },
    region: "cn",
  },
}
