"use client";
import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, FileUp, LoaderCircle, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

type Data = { task: { completed: boolean; participantName: string; organization: string; expiresAt: string }; qualityCase: { title: string; status: string; dueAt: string | null; caseData: Record<string, unknown> }; cycle: { cycleNumber: number }; plan: Record<string, unknown> | null; execution: Record<string, unknown> | null; result: Record<string, unknown> | null; evidence: Array<{ evidence: { id: string; filename: string } }>; readiness: { missing: string[]; warnings: string[]; suggestions: string[] } };
const value = (input: unknown) => typeof input === "string" ? input : ""; const date = (input: unknown) => value(input).slice(0, 10); const count = (input: unknown) => typeof input === "number" ? input : 0;
const STATUS_LABELS: Record<string, string> = { verification_planning: "验证计划", verification_in_progress: "验证执行中", verification_submitted: "等待内部审核", internal_verification_review: "内部审核中", verified_effective: "已确认有效", reopened: "验证失败，已重开" };
export function SupplierVerificationTask({ token }: { token: string }) {
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/verification-tasks/${token}`, { cache: "no-store" }); const payload = await response.json().catch(() => ({})); if (!response.ok) setError(payload.error || "链接不可用"); else setData(payload); }, [token]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const action = async (name: string, body: Record<string, unknown>) => { setBusy(name); setError(""); const response = await fetch(`/api/verification-tasks/${token}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); if (!response.ok) setError(payload.error || "操作失败"); else await load(); setBusy(""); };
  if (!data) return <main className="flex min-h-screen items-center justify-center p-6"><div className="text-sm text-slate-600">{error || <><LoaderCircle className="mr-2 inline size-4 animate-spin" />正在加载验证任务…</>}</div></main>;
  const plan = data.plan || {}, execution = data.execution || {}, result = data.result || {}; const planning = data.qualityCase.status === "verification_planning", progressing = data.qualityCase.status === "verification_in_progress";
  return <main className="min-h-screen bg-slate-50 px-4 py-6 sm:px-6"><div className="mx-auto max-w-5xl space-y-5"><Card className="border-indigo-200 bg-indigo-950 text-white"><CardContent className="p-6"><div className="flex items-center gap-2 text-indigo-200"><ShieldCheck className="size-5" />整改有效性验证</div><h1 className="mt-2 text-2xl font-semibold">{data.qualityCase.title}</h1><p className="mt-2 text-sm text-slate-300">请用实际数据证明改善持续有效。无需了解8D术语。</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><span>负责人<br/><b>{data.task.participantName}</b></span><span>组织<br/><b>{data.task.organization}</b></span><span>周期<br/><b>Cycle {data.cycle.cycleNumber}</b></span><span>状态<br/><b>{STATUS_LABELS[data.qualityCase.status] || data.qualityCase.status}</b></span></div></CardContent></Card>
    {error ? <p className="rounded border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</p> : null}{data.task.completed ? <Card className="border-emerald-200 bg-emerald-50"><CardContent className="flex items-center gap-3 p-6"><CheckCircle2 className="size-6 text-emerald-700" /><div><h2 className="font-semibold">验证结果已提交</h2><p className="text-sm text-emerald-900">正在等待内部人工审核。提交不代表验证已获批准。</p></div></CardContent></Card> : null}
    <Card><CardContent className="p-5"><h2 className="font-semibold">1. 如何证明改善有效</h2><p className="mt-1 text-sm text-slate-600">请定义样本、覆盖范围和明确的通过标准。</p><form className="mt-4 grid gap-4 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void action("plan", { action: "save_plan", plan: Object.fromEntries([...form].map(([key, item]) => [key, key === "sampleSize" ? Number(item) : item])) }); }}><label className="text-sm">验证方法<Input name="method" required defaultValue={value(plan.method)} /></label><label className="text-sm">负责人<Input name="ownerName" required defaultValue={value(plan.ownerName) || data.task.participantName} /></label><label className="text-sm sm:col-span-2">计划说明<Textarea name="description" required defaultValue={value(plan.description)} /></label><label className="text-sm">组织<Input name="organization" required defaultValue={value(plan.organization) || data.task.organization} /></label><label className="text-sm">样本数<Input name="sampleSize" type="number" min="1" required defaultValue={count(plan.sampleSize) || 100} /></label><label className="text-sm sm:col-span-2">样本范围<Textarea name="sampleScope" required defaultValue={value(plan.sampleScope)} placeholder="例如：连续3批，每批500件" /></label><label className="text-sm sm:col-span-2">通过标准<Textarea name="acceptanceCriteria" required defaultValue={value(plan.acceptanceCriteria)} /></label><label className="text-sm">开始日期<Input name="plannedStartAt" type="date" required defaultValue={date(plan.plannedStartAt)} /></label><label className="text-sm">结束日期<Input name="plannedEndAt" type="date" required defaultValue={date(plan.plannedEndAt)} /></label><label className="text-sm">截止日期<Input name="dueAt" type="date" required defaultValue={date(plan.dueAt) || data.qualityCase.dueAt?.slice(0, 10)} /></label>{planning ? <div className="flex items-end gap-2"><Button type="submit" disabled={!!busy}>{busy === "plan" ? "保存中…" : "保存计划"}</Button>{data.plan ? <Button type="button" variant="outline" onClick={() => void action("start", { action: "start" })}>开始验证</Button> : null}</div> : null}</form></CardContent></Card>
    {progressing || data.execution ? <Card><CardContent className="p-5"><h2 className="font-semibold">2. 记录实际执行结果</h2><form className="mt-4 grid gap-4 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void action("result", { action: "save_result", execution: Object.fromEntries([...form].map(([key, item]) => [key, key === "actualSampleSize" ? Number(item) : item])) }); }}><label className="text-sm">执行人<Input name="executorName" required defaultValue={value(execution.executorName) || data.task.participantName} /></label><label className="text-sm">执行组织<Input name="executorOrganization" required defaultValue={value(execution.executorOrganization) || data.task.organization} /></label><label className="text-sm">实际开始<Input name="executionStartAt" type="date" required defaultValue={date(execution.executionStartAt)} /></label><label className="text-sm">实际结束<Input name="executionEndAt" type="date" required defaultValue={date(execution.executionEndAt)} /></label><label className="text-sm sm:col-span-2">实际覆盖范围<Textarea name="actualScope" required defaultValue={value(execution.actualScope)} /></label><label className="text-sm sm:col-span-2">执行说明<Textarea name="executionNotes" required defaultValue={value(execution.executionNotes)} /></label><label className="text-sm">实际样本数<Input name="actualSampleSize" type="number" min="1" required defaultValue={count(result.actualSampleSize) || count(plan.sampleSize)} /></label><label className="text-sm">结果<select name="passFail" defaultValue={value(result.passFail) || "pass"} className="mt-1 h-10 w-full rounded-md border px-3"><option value="pass">符合</option><option value="fail">不符合</option><option value="inconclusive">证据不足</option></select></label><label className="text-sm sm:col-span-2">结果摘要<Textarea name="resultSummary" required defaultValue={value(result.resultSummary)} /></label><label className="text-sm sm:col-span-2">与标准对比<Textarea name="criteriaComparison" required defaultValue={value(result.criteriaComparison)} /></label>{progressing ? <div className="flex gap-2 sm:col-span-2"><Button type="submit" disabled={!!busy}>保存结果</Button>{data.result ? <Button type="button" variant="outline" onClick={() => void action("submit", { action: "submit" })}>提交内部审核</Button> : null}</div> : null}</form></CardContent></Card> : null}
    <Card><CardContent className="p-5"><div className="flex items-center gap-2"><FileUp className="size-4 text-indigo-600" /><h2 className="font-semibold">3. 上传验证证据</h2></div>{progressing && data.result ? <form className="mt-4 flex flex-wrap items-end gap-3" onSubmit={async (event) => { event.preventDefault(); setBusy("file"); const response = await fetch(`/api/verification-tasks/${token}/evidence`, { method: "POST", body: new FormData(event.currentTarget) }); const payload = await response.json().catch(() => ({})); if (!response.ok) setError(payload.error || "上传失败"); else await load(); setBusy(""); }}><label className="text-sm">文件<Input name="file" type="file" required /></label><Button type="submit" variant="outline">上传并关联结果</Button></form> : null}<div className="mt-4 space-y-2">{data.evidence.map(({ evidence }) => <div key={evidence.id} className="rounded border p-3 text-sm">{evidence.filename}</div>)}{!data.evidence.length ? <p className="text-sm text-amber-700">暂未上传证据。可以提交，但内部人员不能批准。</p> : null}</div></CardContent></Card>
    <Card className="border-amber-200"><CardContent className="p-5"><h2 className="font-semibold">提交前提示（仅建议）</h2>{data.readiness.missing.map((item) => <p key={item} className="mt-2 text-sm text-amber-900">缺少：{item}</p>)}{data.readiness.warnings.map((item) => <p key={item} className="mt-2 text-sm text-amber-900">{item}</p>)}</CardContent></Card>
  </div></main>;
}
